-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.AnnotationsKt
-keepclassmembers class kotlinx.serialization.json.** { *** Companion; }
-keepclasseswithmembers class kotlinx.serialization.json.** { kotlinx.serialization.KSerializer serializer(...); }
-keep,includedescriptorclasses class com.deepseno.app.**$$serializer { *; }
-keepclassmembers class com.deepseno.app.** { *** Companion; }
-keepclasseswithmembers class com.deepseno.app.** { kotlinx.serialization.KSerializer serializer(...); }
